<a href="https://colab.research.google.com/github/asakicode/git-study-AIM-/blob/main/260312_12%E1%84%80%E1%85%B5_%E1%84%83%E1%85%A6%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A5%E1%84%87%E1%85%AE%E1%86%AB%E1%84%89%E1%85%A5%E1%86%A8%E1%84%8C%E1%85%A5%E1%86%AB%E1%84%8E%E1%85%A5%E1%84%85%E1%85%B5(%E1%84%91%E1%85%A1%E1%86%AB%E1%84%83%E1%85%A1%E1%84%89%E1%85%B3)_%E1%84%91%E1%85%A1%E1%86%AB%E1%84%83%E1%85%A1%E1%84%89%E1%85%B3%E1%84%80%E1%85%B5%E1%84%8E%E1%85%A9%E1%84%86%E1%85%AE%E1%86%AB%E1%84%87%E1%85%A5%E1%86%B8(2_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 데이터 분석에 필요한 기초 문법들
- query()
    - 성별은 여성인데, pclass 3에 있는 사람들의 fare 평균과 총합을 알고 싶어!
    - 여러 요구조건의 필요한 데이터를 추출하기 위한 기초 문법!
    - query("요구조건 == 값 "), 2개 이상의 조건은 query("요구조건1==값1 & 요구조건2==값2")
- 불린 인덱싱 df[df[True, Fales]]
- sort_values()
- groupby(), agg
- assign()
- merge(), concat() - 1시간 정도 따로 다룰 예정
- cut(), qcut()
- apply()
- melt(), pivot()

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

df=sns.load_dataset('titanic')

- 데이터프레임[데이터프레임[조건불린값]]
    - 내가 원하는 조건 불린값 값들만 추출이 된다. 인덱싱 작업을 해주는 것
    - 여러 개의 다중 조건은?
    - - 데이터프레임[(데이터프레임[조건불린값1]) & (데이터프레임[조건불린값2]).... & n개]

In [2]:
#불린 인덱싱 df[df[True, Fales]]

## 안 -> df[True, Fales]

df['age']>20

0       True
1       True
2       True
3       True
4       True
       ...
886     True
887    False
888    False
889     True
890     True
Name: age, Length: 891, dtype: bool

In [3]:
df.query("age>20 & sex =='male'")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
df[df['age']>70]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [5]:
df[(df['age']>20)&(df['sex']=='male')] ## 내가 원하는 참값만 출력이 되는 것

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [6]:
## 40대 이상 남성과 40대 미만 남성의 실제 요금의 평균이 다를 것 같은데?
## 통계적으로 유의한지 데이터를 한 번 오프라인 테스트 해볼까!?
## 기존에 있는 데이터로 검증

a40over_male =df[(df['age']>=40) & (df['sex']=='male')]['fare'].mean()
a40under_male =df[(df['age']<40) & (df['sex']=='male')]['fare'].mean()

In [7]:
df[(df['age']>=40) & (df['sex']=='male')]['fare'].mean()

np.float64(32.51552110091743)

In [8]:
print(a40over_male, a40under_male)

32.51552110091743 25.606369186046514

In [9]:
## 20살 이상인 사람을 물어보는 것?
## 출력값은 불린으로 떨어진다.
## 불린값을 조건에 대한 것으로 대체하서 넣어서 출력을 하는 것

df[df['age']>20]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

- 데이터프레임은 계속해서 재구조화가 가능하다.
    - 데이터프레임 -> 데이터프레임 -> 데이터프레임 -> 시리즈 -> 스칼라
    - 데이터프레임 재구조화가 가능하다!

In [10]:
df[(df['age']>20)&(df['fare']>20)][['fare','sex']][df[(df['age']>20)&(df['fare']>20)][['fare','sex']]['sex']=='male']['fare'].sum()

np.float64(7720.987499999999)

In [11]:
df[(df['age']>20)&(df['fare']>20)].fare.sum()

np.float64(16556.4084)

In [12]:
df[(df['age']>20)&(df['fare']>20)]['fare'].sum()

np.float64(16556.4084)

In [13]:
df.query('age >20 & fare>20').fare.sum()

np.float64(16556.4084)

In [14]:
df.query('age >20 & fare>20')['fare'].sum()

np.float64(16556.4084)

In [15]:
df.query("sex=='male' & pclass ==3")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [16]:
## 성별이 남성이고, 3클래스인 사람들의 생존자 수 평균 요금
print(df.query("sex=='male' & pclass ==3")[df.query("sex=='male' & pclass ==3")['survived']>0]['fare'].mean())
## 성별이 남성이고, 2클래스인 사람들의 생존자 수 평균 요금
print(df.query("sex=='male' & pclass ==2")[df.query("sex=='male' & pclass ==2")['survived']>0]['fare'].mean())
## 성별이 남성이고, 1클래스인 사람들의 생존자 수 평균 요금
print(df.query("sex=='male' & pclass ==1")[df.query("sex=='male' & pclass ==1")['survived']>0]['fare'].mean())

15.579695744680853
21.095100000000002
74.63732

- sort_values 정렬
    - 내림차순, 오름차순
    - sort_values('컬럼1')
        - 디폴트는 오름차순
        - sort_values('컬럼1', ascending=False) 내림차순
    - 컬럼이 여러 개인 경우
    - sort_values(['컬럼1','컬럼2'])    
    - 컬럼에 따라 내림, 오름차순 지정 가능
    - df[['fare','age']].sort_values(['fare','age'], ascending=['True','False']) 넣으시면 됩니다!
    - 먼저 쓴 컬럼이 기준1, 그다음은 기준2

In [17]:
df[['fare','age']].sort_values('age',ascending=False)

        fare   age
630  30.0000  80.0
851   7.7750  74.0
493  49.5042  71.0
96   34.6542  71.0
116   7.7500  70.5
..       ...   ...
859   7.2292   NaN
863  69.5500   NaN
868   9.5000   NaN
878   7.8958   NaN
888  23.4500   NaN

[891 rows x 2 columns]

In [18]:
df[['fare','age']].sort_values('age')

        fare   age
803   8.5167  0.42
755  14.5000  0.67
644  19.2583  0.75
469  19.2583  0.75
78   29.0000  0.83
..       ...   ...
859   7.2292   NaN
863  69.5500   NaN
868   9.5000   NaN
878   7.8958   NaN
888  23.4500   NaN

[891 rows x 2 columns]

In [19]:
df[['fare','age']].sort_values('age', ascending=False)

        fare   age
630  30.0000  80.0
851   7.7750  74.0
493  49.5042  71.0
96   34.6542  71.0
116   7.7500  70.5
..       ...   ...
859   7.2292   NaN
863  69.5500   NaN
868   9.5000   NaN
878   7.8958   NaN
888  23.4500   NaN

[891 rows x 2 columns]

In [20]:
df[['fare','age']].sort_values(['fare','age'],ascending=[False,False])

         fare   age
679  512.3292  36.0
258  512.3292  35.0
737  512.3292  35.0
438  263.0000  64.0
341  263.0000  24.0
..        ...   ...
481    0.0000   NaN
633    0.0000   NaN
674    0.0000   NaN
732    0.0000   NaN
815    0.0000   NaN

[891 rows x 2 columns]

In [21]:
df[['fare','age']].sort_values(['fare','age'],ascending=[False,False])

         fare   age
679  512.3292  36.0
258  512.3292  35.0
737  512.3292  35.0
438  263.0000  64.0
341  263.0000  24.0
..        ...   ...
481    0.0000   NaN
633    0.0000   NaN
674    0.0000   NaN
732    0.0000   NaN
815    0.0000   NaN

[891 rows x 2 columns]

In [22]:
df[['fare','age']].sort_values(['age','fare'],ascending=[False,True])

         fare   age
630   30.0000  80.0
851    7.7750  74.0
96    34.6542  71.0
493   49.5042  71.0
116    7.7500  70.5
..        ...   ...
306  110.8833   NaN
334  133.6500   NaN
31   146.5208   NaN
527  221.7792   NaN
557  227.5250   NaN

[891 rows x 2 columns]

### groupby 요약 집계
- 데이터 요약 집계
- 데이터 분석의 경우 요약 집계할 때 많이 사용한다.
- df.groupby('묶을 컬럼')
    - df.groupby(['컬럼1','컬럼2'])
    
- groupby 내에서 추출
    - get_group(기준값)
    - get_group((기준1,기준2))
    
- groupby는 기초 통계와 함께 많이 사용한다.
- agg함수로 많이 사용한다.
- 다양한 기초 통계치를 한 번에 사용한다면?
    - agg함수
    - df.groubpy('기준컬럼').agg(만들 컬럼명 =(그룹할 컬럼1, 원하는 요약통계치1),
                                           (그룹할 컬럼2, 원하는 요약통계치2)...n)

In [23]:
df_sur= df.groupby('survived')

In [24]:
for i,j in df_sur:
    display(i,j)

0

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [25]:
df_sex= df.groupby('sex')

In [26]:
df_sex

In [27]:
for i, j in df_sex:
    print(i)
    print(j)

female
     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
8           1       3  female  27.0      0      2  11.1333        S   Third
9           1       2  female  14.0      1      0  30.0708        C  Second
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
880         1       2  female  25.0      0      1  26.0000        S  Second
882         0       3  female  22.0      0      0  10.5167        S   Third
885         0       3  female  39.0      0      5  29.1250        Q   Third
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third

       who  adult_male deck  embark_town alive  alone
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
8    woman       False  NaN  Southampton   yes  False
9    child       False  NaN    Cherbourg   yes  False
..     ...         ...  ...          ...   ...    ...
880  woman       False  NaN  Southampton   yes  False
882  woman       False  NaN  Southampton    no   True
885  woman       False  NaN   Queenstown    no  False
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False

[314 rows x 15 columns]
male
     survived  pclass   sex   age  sibsp  parch     fare embarked   class  \
0           0       3  male  22.0      1      0   7.2500        S   Third
4           0       3  male  35.0      0      0   8.0500        S   Third
5           0       3  male   NaN      0      0   8.4583        Q   Third
6           0       1  male  54.0      0      0  51.8625        S   First
7           0       3  male   2.0      3      1  21.0750        S   Third
..        ...     ...   ...   ...    ...    ...      ...      ...     ...
883         0       2  male  28.0      0      0  10.5000        S  Second
884         0       3  male  25.0      0      0   7.0500        S   Third
886         0       2  male  27.0      0      0  13.0000        S  Second
889         1       1  male  26.0      0      0  30.0000        C   First
890         0       3  male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
4      man        True  NaN  Southampton    no   True
5      man        True  NaN   Queenstown    no   True
6      man        True    E  Southampton    no   True
7    child       False  NaN  Southampton    no  False
..     ...         ...  ...          ...   ...    ...
883    man        True  NaN  Southampton    no   True
884    man        True  NaN  Southampton    no   True
886    man        True  NaN  Southampton    no   True
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[577 rows x 15 columns]

In [28]:
## 2개 이상 컬럼으로 묶기
df_sex_pclass= df.groupby(['sex','pclass'])

In [29]:
for i , j in df_sex_pclass:
    display(i,j )

('female', np.int64(1))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

('female', np.int64(2))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
41,0,2,female,27.0,1,0,21.0000,S,Second,woman,False,NaN,Southampton,no,False
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
53,1,2,female,29.0,1,0,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
854,0,2,female,44.0,1,0,26.0000,S,Second,woman,False,NaN,Southampton,no,False
865,1,2,female,42.0,0,0,13.0000,S,Second,woman,False,NaN,Southampton,yes,True
866,1,2,female,27.0,1,0,13.8583,C,Second,woman,False,NaN,Cherbourg,yes,False
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False

('female', np.int64(3))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

('male', np.int64(1))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
34,0,1,male,28.0,1,0,82.1708,C,First,man,True,NaN,Cherbourg,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
839,1,1,male,NaN,0,0,29.7000,C,First,man,True,C,Cherbourg,yes,True
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

('male', np.int64(2))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
17,1,2,male,NaN,0,0,13.0,S,Second,man,True,NaN,Southampton,yes,True
20,0,2,male,35.0,0,0,26.0,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0,S,Second,man,True,D,Southampton,yes,True
33,0,2,male,66.0,0,0,10.5,S,Second,man,True,NaN,Southampton,no,True
70,0,2,male,32.0,0,0,10.5,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,0,2,male,28.0,0,1,33.0,S,Second,man,True,NaN,Southampton,no,False
861,0,2,male,21.0,1,0,11.5,S,Second,man,True,NaN,Southampton,no,False
864,0,2,male,24.0,0,0,13.0,S,Second,man,True,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5,S,Second,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0,S,Second,man,True,NaN,Southampton,no,True

('male', np.int64(3))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

- 내가 원하는 데이터프레임만 추출하고 싶어!
- groupby 상태에서 추출인 경우

In [30]:
df_sex.get_group('male')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [31]:
df_sex.get_group('female')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [32]:
df_sex_pclass.get_group(('male', 2))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
17,1,2,male,NaN,0,0,13.0,S,Second,man,True,NaN,Southampton,yes,True
20,0,2,male,35.0,0,0,26.0,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0,S,Second,man,True,D,Southampton,yes,True
33,0,2,male,66.0,0,0,10.5,S,Second,man,True,NaN,Southampton,no,True
70,0,2,male,32.0,0,0,10.5,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,0,2,male,28.0,0,1,33.0,S,Second,man,True,NaN,Southampton,no,False
861,0,2,male,21.0,1,0,11.5,S,Second,man,True,NaN,Southampton,no,False
864,0,2,male,24.0,0,0,13.0,S,Second,man,True,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5,S,Second,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0,S,Second,man,True,NaN,Southampton,no,True

In [33]:
df_sex_pclass.get_group(('male', 3))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [34]:
print(df_sex_pclass.get_group(('female', 1))['fare'].sum())
print(df_sex_pclass.get_group(('female', 2))['fare'].sum())
print(df_sex_pclass.get_group(('female', 3))['fare'].sum())

print(df_sex_pclass.get_group(('male', 1))['fare'].sum())
print(df_sex_pclass.get_group(('male', 2))['fare'].sum())
print(df_sex_pclass.get_group(('male', 3))['fare'].sum())

9975.825
1669.7292
2321.1086
8201.5875
2132.1125
4393.5865

In [35]:
## 컬럼이 여러 개 들어갈 수 있다.
df.groupby(['sex','pclass'])['fare'].sum()

sex     pclass
female  1         9975.8250
        2         1669.7292
        3         2321.1086
male    1         8201.5875
        2         2132.1125
        3         4393.5865
Name: fare, dtype: float64

In [36]:
df.groupby(['sex','pclass'])[['fare','age']].mean()

                     fare        age
sex    pclass
female 1       106.125798  34.611765
       2        21.970121  28.722973
       3        16.118810  21.750000
male   1        67.226127  41.281386
       2        19.741782  30.740707
       3        12.661633  26.507589

In [37]:
df.groupby(['sex','pclass'])[['fare','age']].agg(
    fare_mean=('fare','mean'),
    fare_sum=('fare','sum'),
    age_mean=('age','mean'),
    age_cnt=('age','count'),
)

                fare_mean   fare_sum   age_mean  age_cnt
sex    pclass
female 1       106.125798  9975.8250  34.611765       85
       2        21.970121  1669.7292  28.722973       74
       3        16.118810  2321.1086  21.750000      102
male   1        67.226127  8201.5875  41.281386      101
       2        19.741782  2132.1125  30.740707       99
       3        12.661633  4393.5865  26.507589      253

In [38]:
## 내가 원하는 요구조건의 생존율을 보고싶어!
## 나이는 30대 이상, 요금은 20이상, pclass 3인데 그중 남성인 경우에 생존자 수
df.query("age>30 & fare>20 & pclass==3 & sex =='male'").groupby('sex')['survived'].sum()

sex
male    2
Name: survived, dtype: int64

In [39]:
df.query("age>30 & fare>20 & pclass==3 & sex =='male'")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
74,1,3,male,32.0,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True
360,0,3,male,40.0,1,4,27.9000,S,Third,man,True,NaN,Southampton,no,False
548,0,3,male,33.0,1,1,20.5250,S,Third,man,True,NaN,Southampton,no,False
595,0,3,male,36.0,1,1,24.1500,S,Third,man,True,NaN,Southampton,no,False
811,0,3,male,39.0,0,0,24.1500,S,Third,man,True,NaN,Southampton,no,True
838,1,3,male,32.0,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True

In [40]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [41]:
def min_max(x):
    return x.min() - x.max()

In [42]:
## 자기가 원하는 함수를 대입해서 사용할 수 있다.
df.groupby('sex')['fare'].agg(min_max)

sex
female   -505.5792
male     -512.3292
Name: fare, dtype: float64

In [43]:
df.groupby('pclass')[['fare','age']].describe()

         fare                                                                \
        count       mean        std  min       25%      50%   75%       max
pclass
1       216.0  84.154687  78.380373  0.0  30.92395  60.2875  93.5  512.3292
2       184.0  20.662183  13.417399  0.0  13.00000  14.2500  26.0   73.5000
3       491.0  13.675550  11.778142  0.0   7.75000   8.0500  15.5   69.5500

          age
        count       mean        std   min   25%   50%   75%   max
pclass
1       186.0  38.233441  14.802856  0.92  27.0  37.0  49.0  80.0
2       173.0  29.877630  14.001077  0.67  23.0  29.0  36.0  70.0
3       355.0  25.140620  12.495398  0.42  18.0  24.0  32.0  74.0

- assign 함수
- 파생변수 추가시 많이 사용

In [44]:
df['agefare']=df['age']+df['fare']

- 여러 개의 파생변수를 만들때
- assign(변수명1 = 파생변수식1,
         변수명2 = 파생변수식2...n)

In [45]:
df.assign(
    agefare1 = df['age']+df['fare'],
    agefare2 = df['age']-df['fare']
)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,agefare,agefare1,agefare2
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,29.2500,29.2500,14.7500
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,109.2833,109.2833,-33.2833
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,33.9250,33.9250,18.0750
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,88.1000,88.1000,-18.1000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,43.0500,43.0500,26.9500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,40.0000,40.0000,14.0000
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,49.0000,49.0000,-11.0000
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN,NaN,NaN
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,56.0000,56.0000,-4.0000
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,39.7500,39.7500,24.2500

In [46]:
## lambda
df.assign(agefare= lambda x : x['age']+ x['fare'])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,agefare
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,29.2500
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,109.2833
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,33.9250
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,88.1000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,43.0500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,40.0000
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,49.0000
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,56.0000
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,39.7500

### 데이터 병합

- why? 병합하는 이유
    - 기업에는 모든 DB데이터가 나눠서 메타데이터 정리되어 있다.
    - 데이터 병합은 필수
- concat
    - 덩어리와 덩어리가 axis기준으로 붙여지는 것
    - 데이터프레임 + 데이터프레임 붙여지는 형태
    - pd.concat([df1,df2], axis= 1,0 둘 중 하나)
- merge
    - 공통된 컬럼이 존재
    - 병합 방법이 inner, left, right ,outer 조인연산방법
    - join
    - pd.merge(df1,df2, how='기준',on =공통컬럼)

In [47]:
test1 =pd.DataFrame({'학회원분반번호':[1,2,3,4,5],
             '학회원분반':['Python','R','SQL','데이터전처리','데이터모델링']})

test2 =pd.DataFrame({'학회원분반번호':[1,2,3,4,6],
             '학회원수':[100,200,300,400,500]})

In [48]:
## merge
pd.merge(test1,test2, how='inner',on='학회원분반번호')

   학회원분반번호   학회원분반  학회원수
0        1  Python   100
1        2       R   200
2        3     SQL   300
3        4  데이터전처리   400

In [49]:
pd.merge(test1,test2, how='outer',on='학회원분반번호')

   학회원분반번호   학회원분반   학회원수
0        1  Python  100.0
1        2       R  200.0
2        3     SQL  300.0
3        4  데이터전처리  400.0
4        5  데이터모델링    NaN
5        6     NaN  500.0

In [50]:
pd.concat([test1, test2],axis =1)

   학회원분반번호   학회원분반  학회원분반번호  학회원수
0        1  Python        1   100
1        2       R        2   200
2        3     SQL        3   300
3        4  데이터전처리        4   400
4        5  데이터모델링        6   500

In [51]:
pd.concat([test1, test2],axis =0)

   학회원분반번호   학회원분반   학회원수
0        1  Python    NaN
1        2       R    NaN
2        3     SQL    NaN
3        4  데이터전처리    NaN
4        5  데이터모델링    NaN
0        1     NaN  100.0
1        2     NaN  200.0
2        3     NaN  300.0
3        4     NaN  400.0
4        6     NaN  500.0

In [52]:
display(test1)
display(test2)

   학회원분반번호   학회원분반
0        1  Python
1        2       R
2        3     SQL
3        4  데이터전처리
4        5  데이터모델링

   학회원분반번호  학회원수
0        1   100
1        2   200
2        3   300
3        4   400
4        6   500

- cut() , qcut()
- 데이터를 나눈다.
- 데이터 구간화 binning 작업시 사용
    - 연속형은 고정된 간격인 bins 나누는 것
    - 수치형 데이터는 범주형 데이터로 구간화 변환   
- cut
    - 구간의 크기가 일정하게, 값의 분포는 고려하지 않는다. 구간 개수는 우리가 직접 설정이 가능하고
    - pd.cut(데이터프레임_시리즈형태, bins= 지정된 값)
- qcut
    - 분위수 Quantile 기준을 나누는 차이
    - 데이터의 분포가 개수가 거의 동일한 그룹으로 나뉘어 진다.
    - 등간격이 아니라 분포를 고려해서 구간을 자동으로 설정
    - 구간에 속하는 데이터의 개수는 동일하다.
    - qd.qcut(데이터프레임_시리즈형태, q=지정)

In [53]:
#pd.cut(df['age'],bins=4).value_counts()

df['age_cut']=pd.cut(df['age'],bins=4)

In [54]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,agefare,age_cut
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,29.2500,"(20.315, 40.21]"
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,109.2833,"(20.315, 40.21]"
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,33.9250,"(20.315, 40.21]"
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,88.1000,"(20.315, 40.21]"
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,43.0500,"(20.315, 40.21]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,40.0000,"(20.315, 40.21]"
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,49.0000,"(0.34, 20.315]"
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN,NaN
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,56.0000,"(20.315, 40.21]"
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,39.7500,"(20.315, 40.21]"

## age 구간을 나눠보자

- age < 19 : child
- 19<= age< 70: Adult
- 나머지는 Senior

- apply 함수를 통해 데이터프레임의 전체 값에 적용시킬 수 있다. , 함수 등을

In [55]:
df['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [56]:


pd.qcut(df['age'], q=4).value_counts()

age
(20.125, 28.0]     183
(0.419, 20.125]    179
(38.0, 80.0]       177
(28.0, 38.0]       175
Name: count, dtype: int64

2주차 과제 제출용 복습 예시들

In [57]:
# DataFrame 확인
print(type(df))

# Series 확인 (age 열만 추출)
age_series = df['age']
print(type(age_series))
print(age_series.head())

# 시리즈의 기초 통계 확인
print(f"평균 나이: {age_series.mean():.2f}")

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64
평균 나이: 29.70

In [58]:
# 예제: 3등석(pclass == 3)에 탄 여성(sex == 'female') 데이터만 추출
cond_pclass = (df['pclass'] == 3)
cond_sex = (df['sex'] == 'female')

result_bool = df[cond_pclass & cond_sex]
result_bool.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,agefare,age_cut
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,33.9250,"(20.315, 40.21]"
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False,38.1333,"(20.315, 40.21]"
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,20.7000,"(0.34, 20.315]"
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True,21.8542,"(0.34, 20.315]"
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False,49.0000,"(20.315, 40.21]"

In [59]:
# 예제: 나이가 30세 이상이면서 혼자 타지 않은(alone == False) 승객 추출
result_query = df.query("age >= 30 and alone == False")
result_query.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,agefare,age_cut
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,109.2833,"(20.315, 40.21]"
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,88.1000,"(20.315, 40.21]"
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False,70.2750,"(20.315, 40.21]"
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False,49.0000,"(20.315, 40.21]"
25,1,3,female,38.0,1,5,31.3875,S,Third,woman,False,NaN,Southampton,yes,False,69.3875,"(20.315, 40.21]"

In [ ]:
# 예제 1: 좌석 등급(pclass)별 평균 생존율(survived) 구하기
print(df.groupby('pclass')['survived'].mean())

# 예제 2: 성별(sex) 및 좌석 등급(pclass)별 요금(fare)의 중앙값과 평균 구하기
# agg()를 사용하면 여러 함수를 한 번에 적용할 수 있습니다.
group_result = df.groupby(['sex', 'pclass'])['fare'].agg(['mean', 'median'])
print(group_result)