<a href="https://colab.research.google.com/github/asakicode/git-study-AIM-/blob/main/BDAI%EC%A0%84%EC%B2%98%EB%A6%AC_4%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

import seaborn as sns
df = sns.load_dataset("titanic")

### Series.rank, DataFrame.rank
- method(동점 처리)
----
        - """
            s.rank(
                method='average',    # 'average' | 'min' | 'max' | 'first' | 'dense'
                ascending=True,      # True: 작은 값이 1위, False: 큰 값이 1위
                na_option='keep',    # 'keep' | 'top' | 'bottom' (NaN의 상대적 위치)
                pct=False            # True면 [0,1] 구간의 백분위 비율로 반환
            )
         - """
----
    - 'average'(기본): 동점들의 순위를 평균으로 부여 (예: 2등,3등이면 둘 다 2.5)
    - 'min': 동점 모두 가장 작은 등수(=공동 2등이면 둘 다 2)
    - 'max': 동점 모두 가장 큰 등수(=둘 다 3)
    - 'dense': 중간 등수 건너뛰지 않음 (1,2,2,3,4…)
    - 'first': 원래 등장 순서를 타이브레이커로 사용(재현성 필요할 때 유용)
- ascending: 내림차순 랭킹(값 클수록 1위)이면 ascending=False.
- pct=True: 랭크를 0~1 사이 비율로 변환(누적백분위 느낌).

In [ ]:
import pandas as pd

s =pd.Series([10,20,20,40,None])

/Users/ukjunjeoung/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [ ]:
## 오름차순 평균-> 10 ->1.0, 20 -> 2.5
s.rank()

0    1.0
1    2.5
2    2.5
3    4.0
4    NaN
dtype: float64

In [ ]:
s.rank(ascending=False, method='first')

0    4.0
1    2.0
2    3.0
3    1.0
4    NaN
dtype: float64

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
import pandas as pd
import numpy as np

# 1. 예제 Series 생성
# - 동점값 여러 개 포함 (20 세 개, 50 두 개)
# - NaN 값 포함
# - 음수, 양수, 큰 값 섞음
s = pd.Series([30, 10, 20, 20, 50, 20, 50, np.nan, 5, 100, np.nan])

print("=== 원본 Series ===")
print(s)
print()

# 2. 기본 rank()
# - 오름차순(ascending=True), 동점은 평균(method='average')
# - NaN은 NaN으로 유지
print("=== 기본 rank() (ascending=True, method='average') ===")
print(s.rank())
# 5→1, 10→2, 20들(3,4,5)→4.0, 30→6, 50들(7,8)→7.5, 100→9, NaN→NaN
print()

# 3. method='min'
# - 동점값에 대해 '최소 등수'를 부여
# - SQL RANK()와 유사
print("=== method='min' ===")
print(s.rank(method='min'))
# 20 세 개 모두 3, 50 두 개 모두 7
print()

# 4. method='max'
# - 동점값에 대해 '최대 등수'를 부여
print("=== method='max' ===")
print(s.rank(method='max'))
# 20 세 개 모두 5, 50 두 개 모두 8
print()

# 5. method='dense'
# - 중간 등수를 건너뛰지 않음
# - SQL의 DENSE_RANK()와 동일
print("=== method='dense' ===")
print(s.rank(method='dense'))
# 5→1, 10→2, 20(3개)→3, 30→4, 50(2개)→5, 100→6
print()

# 6. method='first'
# - 등장 순서대로 순위를 부여 (동점이라도 순서에 따라 달라짐)
print("=== method='first' ===")
print(s.rank(method='first'))
# 20 세 개라도 3,4,5 순으로 각각 다르게 등수 부여됨
print()

# 7. ascending=False
# - 내림차순 정렬 (큰 값이 1등)
print("=== ascending=False (내림차순) ===")
print(s.rank(ascending=False))
# 100→1, 50들→(2+3)/2=2.5, 30→4, 20들→6, 10→8, 5→9, NaN→NaN
print()

# 8. pct=True
# - 등수를 전체 유효 값 개수로 나눈 '백분위 비율' 반환
print("=== pct=True (백분위 비율) ===")
print(s.rank(pct=True))
# 1~9등을 9로 나눈 값 (NaN 제외)
print()

# 정리
# - method 옵션에 따라 동점 처리 방식이 달라져 값이 달라질 수 있음
# - ascending=False는 등수 순서를 뒤집음
# - pct=True는 정규화된 비율값을 반환함
# - rank() 사용할 때는 method와 ascending을 명시하는 것이 안전함

=== 원본 Series ===
0      30.0
1      10.0
2      20.0
3      20.0
4      50.0
5      20.0
6      50.0
7       NaN
8       5.0
9     100.0
10      NaN
dtype: float64

=== 기본 rank() (ascending=True, method='average') ===
0     6.0
1     2.0
2     4.0
3     4.0
4     7.5
5     4.0
6     7.5
7     NaN
8     1.0
9     9.0
10    NaN
dtype: float64

=== method='min' ===
0     6.0
1     2.0
2     3.0
3     3.0
4     7.0
5     3.0
6     7.0
7     NaN
8     1.0
9     9.0
10    NaN
dtype: float64

=== method='max' ===
0     6.0
1     2.0
2     5.0
3     5.0
4     8.0
5     5.0
6     8.0
7     NaN
8     1.0
9     9.0
10    NaN
dtype: float64

=== method='dense' ===
0     4.0
1     2.0
2     3.0
3     3.0
4     5.0
5     3.0
6     5.0
7     NaN
8     1.0
9     6.0
10    NaN
dtype: float64

=== method='first' ===
0     6.0
1     2.0
2     3.0
3     4.0
4     7.0
5     5.0
6     8.0
7     NaN
8     1.0
9     9.0
10    NaN
dtype: float64

=== ascending=False (내림차순) ===
0     4.0
1     8.0
2     6.0
3     6.0
4     2.5
5     6.0
6     2.5
7     NaN
8     9.0
9     1.0
10    NaN
dtype: float64

=== pct=True (백분위 비율) ===
0     0.666667
1     0.222222
2     0.444444
3     0.444444
4     0.833333
5     0.444444
6     0.833333
7          NaN
8     0.111111
9     1.000000
10         NaN
dtype: float64

In [ ]:
## groupby pclass, fare 같이 묶어서 진행

##새로운 컬럼을 만들기
df['fare_rk_in_pclass'] = df.groupby('pclass')['fare'].rank(method='first', ascending=False)

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_rk_in_pclass
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,421.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,98.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,263.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,121.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,219.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,142.0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,173.0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,66.0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,174.0
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,397.0

In [ ]:
df['fare'].rank(method='min')

0       71.0
1      789.0
2      224.0
3      746.0
4      243.0
       ...
886    387.0
887    652.0
888    546.0
889    652.0
890    107.0
Name: fare, Length: 891, dtype: float64

### Pivot
- pivot: 재배열 전용. 동일한 (index, columns) 조합에 중복이 없어야 함. 집계(aggregation) 안 함.
- pivot_table: 집계 포함 피벗. 중복이 있어도 aggfunc로 요약. 가장 범용적.
- crosstab: 범주×범주 빈도표(count) 만들기에 특화. 비율(normalize)도 간편.

- pivot
    - df.pivot(index='행으로 둘 컬럼', columns = '열로 둘 컬럼', values='셀에 채울 값')

In [ ]:
# pclass, sex 따른 fare의 평균을 둔다.
avg_fare=df.groupby(['pclass','sex'])['fare'].mean().reset_index() ## pivot을 돌리기 위해 다시 리셋 인덱스!

In [ ]:
#avg_fare=df.groupby(['pclass','sex'])['fare'].mean()

In [ ]:
avg_fare

   pclass     sex        fare
0       1  female  106.125798
1       1    male   67.226127
2       2  female   21.970121
3       2    male   19.741782
4       3  female   16.118810
5       3    male   12.661633

In [ ]:
avg_fare.pivot(index='pclass',columns = 'sex', values='fare')

sex         female       male
pclass
1       106.125798  67.226127
2        21.970121  19.741782
3        16.118810  12.661633

In [ ]:
avg_fare

pclass  sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64

- pivot_table
    - pd.pivot_table(
        df,
        values='',
        index=[''],
        columns = [''],
        aggfunc = 'mean' , # mean,sum..
        fill_value = None, # 결측치는 어떻게 할 것인가?
        ...)

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_rk_in_pclass
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,421.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,98.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,263.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,121.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,219.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,142.0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,173.0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,66.0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,174.0
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,397.0

In [ ]:
pd.pivot_table(
    df, values='fare',
    index ='pclass', columns ='sex', aggfunc='mean').round(3)

sex      female    male
pclass
1       106.126  67.226
2        21.970  19.742
3        16.119  12.662

- crosstab
    - pd.crosstab(
    index= .., coluns = ..,
    values =None., aggfunc=..,
    normalize=T/F...
    )

In [ ]:
## 범주 x 범주의 빈도
pd.crosstab(df['pclass'], df['sex'], margins=True)

sex     female  male  All
pclass
1           94   122  216
2           76   108  184
3          144   347  491
All        314   577  891

In [ ]:
pd.crosstab(df['pclass'], df['sex'], normalize='all')

sex       female      male
pclass
1       0.105499  0.136925
2       0.085297  0.121212
3       0.161616  0.389450

In [ ]:
pd.crosstab(df['pclass'], df['sex'], values=df['fare'], aggfunc='mean')

sex         female       male
pclass
1       106.125798  67.226127
2        21.970121  19.741782
3        16.118810  12.661633

In [ ]:
pd.pivot_table(
    df, values='fare',
    index ='pclass', columns ='sex', aggfunc='mean').round(3)

sex      female    male
pclass
1       106.126  67.226
2        21.970  19.742
3        16.119  12.662

# 심슨의 역설

- 단순 평균에 대한 비교는 잘못된 분석의 결과를 초래한다.
- 교란변수(confounder)를 그룹화기준에 포함하지 않으면 잘못된 결과를 해석할 수 있다.

In [ ]:
overall = df.groupby('sex')['survived'].mean()

In [ ]:
print(overall)

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

- 여성이 대부분 구조에 우선이었다!

In [ ]:
## 잘못된 groupby

df.groupby('sex')['fare'].mean()

sex
female    44.479818
male      25.523893
Name: fare, dtype: float64

- 여성이 더 비싼 티켓을 샀으니 생존율이 높았다. 단순한 결론이 나올 수 있다.

In [ ]:
by_class=df.groupby(['pclass','sex'])['survived'].mean().unstack()

In [ ]:
by_class

sex       female      male
pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

In [ ]:
## 등급의 따른 분포를 살펴보자!

class_dist=pd.crosstab(df['sex'], df['pclass'], normalize='index')

In [ ]:
pd.crosstab(df['sex'], df['pclass'])

pclass    1    2    3
sex
female   94   76  144
male    122  108  347

In [ ]:
print(class_dist)

pclass         1         2         3
sex
female  0.299363  0.242038  0.458599
male    0.211438  0.187175  0.601386

- 심슨 정리 : 단순하게 전체로만 데이터를 바라보면 -> 훨씬 과장돼 보이는 것!